name: "PR Auto-Merge when opend"

on:
  pull_request:
    types: [created, opened, reopened]

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  merge:
    name: "Auto Merge on time"
    if: ${{ github.event.pull_request.baseRefName != 'main' && endsWith(github.event.pull_request.title, '#auto-merge') }}
    runs-on: "ubuntu-latest"
    
    steps:
      - name: "Merge pull request"
        uses: "actions/github-script@v3"
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
              try { 
                 if(github.event.pull_request.mergeable === "CONFLICTING") {
                   await github.pulls.update({
                      owner: context.repo.owner,
                      repo: context.repo.repo,
                      pull_number: github.event.pull_request.number,
                      state: "closed"
                    })
                 } else {
                   await github.pulls.merge({
                      owner: context.repo.owner,
                      repo: context.repo.repo,
                      pull_number: github.event.pull_request.number,
                      merge_method: "squash"
                   })
                 }
               } catch (e) {
                 console.log("error", e);
               }

